version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      # Aquí podrías agregar variables necesarias para conectar al DB
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: alexis
      DB_PASSWORD: admin123

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Asegúrate de que el contenedor del frontend esté sirviendo en el puerto 80
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:3000"  # Aquí puedes usar una variable para la URL del backend en el frontend

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alexis
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
