version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: ["node", "src/server.js"]  # Asegúrate de que se ejecute en modo desarrollo

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"  # Exponemos el puerto 8080 para el frontend en desarrollo
    depends_on:
      - backend
    command: ["npm", "run", "dev"]  # Asegúrate de que se ejecute en modo desarrollo

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alexis
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
